[alias]
r = "run --release --quiet --"

translate = "r translate"
tl = "translate"

edit-translate = "r edit-translate"
etl = "edit-translate"

extract = "r extract"
x = "extract"

pack = "r pack"
p = "pack"

read-lines = "r read-lines"
rl = "read-lines"
