pub mod csv;
pub mod helpers;
pub mod mbe;
pub mod mvgl;

use std::borrow::Cow;

use num::FromPrimitive;
use num_derive::FromPrimitive;

macro_rules! create_characters {
    ($($variant: ident $name: literal $nb: literal),+) => {
        #[repr(u32)]
        #[derive(FromPrimitive, Clone, Copy, Debug, PartialEq, Eq)]
        pub enum Character {
            $($variant = $nb),+
        }

        impl Character {
            pub fn name(self) -> &'static str {
                match self {
                    $(Self::$variant => $name),+
                }
            }

            pub fn from_name(value: &str) -> Option<Self> {
                Some(match value {
                    $($name => Self::$variant,)+
                    _ => return None,
                })
            }
        }
    };
}

create_characters! {
//  Variant                 Name                        Numeric Value
    None                    "None"                      0x0,
    Takumi                  "Takumi Sumino"             0x1,
    Takemaru                "Takemaru Yakushiji"        0x2,
    Hiruko                  "Hiruko Shizuhara"          0x3,
    Darumi                  "Darumi Amemiya"            0x4,
    Eito                    "Eito Aotsuki"              0x5,
    Tsubasa                 "Tsubasa Kawana"            0x6,
    Gaku                    "Gaku Maruko"               0x7,
    Ima                     "Ima Tsukumo"               0x8,
    Kako                    "Kako Tsukumo"              0x9,
    Shouma                  "Shouma Ginzaki"            0xA,
    Nozomi                  "Nozomi Kirifuji"           0xB,
    Kurara                  "Kurara Oosuzuki"           0xC,
    Kyoshika                "Kyoshika Magadori"         0xD,
    Yugamu                  "Yugamu Omokage"            0xE,
    Moko                    "Moko Mojiro"               0xF,
    Eva                     "Eva"                       0x10,
    Shion                   "Shion"                     0x11,
    Sirei                   "Sirei"                     0x12,
    Nigou                   "Nigou"                     0x13,
    TakumiCombatForm        "Takumi Sumino (SDU)"       0x63,
    Murvrum                 "Murvrum"                   0x65, // Paragon of Order
    Pakron                  "Pakron"                    0x66, // Paragon of Virtue
    Addamaque               "Addamaque"                 0x67, // Paragon of Hatred
    Quenzelle               "Quenzelle"                 0x68, // Paragon of Repulsion
    Parmith                 "Parmith"                   0x69, // Paragon of Devotion
    EvaParagon              "Eva (Paragon of Nature)"   0x6A, // Paragon of Nature
    ZenTa                   "Zen'ta"                    0x6B, // Paragon of Harmony
    VallaGarzo              "Valla-Garzo"               0x6C, // Paragon of Indomitability
    Szanshin                "Szanshin"                  0x6D, // Paragon of Salvation
    Nyewgank                "Nyewgank"                  0x6E, // Paragon of Charity
    Turamtammi              "Turamtammi"                0x6F, // Paragon of Reverie
    Dahlxia                 "Dahl'xia"                  0x70, // Paragon of Warfare
    Vexhness                "V'ehxness"                 0x71, // Paragon of Hope
    TakumisMom              "Takumi's Mom"              0xC9,
    KaruaKashimiya          "Karua Kashimiya"           0xCA,
    Karua                   "Karua"                     0xCB,
    MrSirei                 "Mr. Sirei"                 0xCC,
    MrNigou                 "Mr. Nigou"                 0xCD,
    PersonInLeapSuit        "Person in Leap Suit"       0xCE,
    GhostlyWoman            "Ghostly Woman"             0xCF,
    FigureInBlack           "Figure in Black"           0xD0,
    TheOldMan               "The Old Man"               0xD1,
    Kamyuhn                 "Kamyuhn"                   0xD2,
    Villager                "Villager"                  0xD3,
    VillageWoman            "Village Woman"             0xD4,
    VillageBoy              "Village Boy"               0xD5,
    VillageGirl             "Village Girl"              0xD6,
    KakoG                   "Kako-G"                    0xD7,
    VillageMan              "Village Man"               0xD8,
    VillageMan2             "Village Man 2"             0xD9,
    VillageWoman2           "Village Woman 2"           0xDA,
    OtherTakumi             "Other Takumi"              0xFB,
    OtherTakemaru           "Other Takemaru"            0xFC,
    OtherHiruko             "Other Hiruko"              0xFD,
    OtherDarumi             "Other Darumi"              0xFE,
    OtherEito               "Other Eito"                0xFF,
    OtherTsubasa            "Other Tsubasa"             0x100,
    OtherGaku               "Other Gaku"                0x101,
    OtherIma                "Other Ima"                 0x102,
    OtherKako               "Other Kako"                0x103,
    OtherShouma             "Other Shouma"              0x104,
    OtherNozomi             "Other Nozomi"              0x105,
    OtherKurara             "Other Kurara"              0x106,
    OtherKyoshika           "Other Kyoshika"            0x107,
    OtherYugamu             "Other Yugamu"              0x108,
    OtherMoko               "Other Moko"                0x109,
    OtherEva                "Other Eva"                 0x10A,
    OtherShion              "Other Shion"               0x10B,
    OtherSirei              "Other Sirei"               0x10C,
    OtherNigou              "Other Nigou"               0x10D,
    OtherVexhness           "Other V'ehxness"           0x10E,
    OtherEito2              "Other Eito 2"              0x10F,
    OtherEito3              "Other Eito 3"              0x110,
    OtherEito4              "Other Eito 4"              0x111,
    OtherEito5              "Other Eito 5"              0x112,
    FuturanChild            "Futuran Child"             0x113,
    Sponsor                 "Sponsor"                   0x114,
    Sponsor2                "Sponsor 2"                 0x115,
    Sponsor3                "Sponsor 3"                 0x116,
    Sponsor4                "Sponsor 4"                 0x117,
    Sponsor5                "Sponsor 5"                 0x118,
    Sponsor6                "Sponsor 6"                 0x119,
    VillageBoy2             "Village Boy 2"             0x11A,
    FuturanGirl             "Futuran Girl"              0x11B,
    SponsorKakoG            "Sponsor - Kako-G"          0x11C,
    SponsorEito             "Sponsor - Eito"            0x11D,
    All                     "All"                       0x12D,
    Unknown                 "???"                       0x12E,
    DefenseSystem           "Defense System"            0x12F,
    Announcement            "Announcement (Unused)"     0x130,
    Thought                 "<Thought>"                 0x131, // empty internally
    PASystem                "PA System"                 0x132,
    Bell                    "Bell"                      0x133,
    Lock                    "Lock"                      0x134,
    Doorbell                "Doorbell"                  0x135,
    Door                    "Door"                      0x136,
    Mother                  "Mother"                    0x137,
    YoungMan                "Young Man"                 0x138,
    Father                  "Father"                    0x139,
    Humanity                "Humanity"                  0x13A,
    TakumiII                "Takumi II"                 0x13B,
    TakumiIII               "Takumi III"                0x13C,
    TakumiIV                "Takumi IV"                 0x13D,
    Letter                  "Letter"                    0x13E,
    ShadowyFigure           "Shadowy Figure"            0x13F,
    Noise                   "Noise"                     0x140,
    Message                 "Message"                   0x141,
    Doll                    "Doll"                      0x142,
    TakumiV                 "Takumi V"                  0x143,
    HirukoV                 "Hiruko V"                  0x144,
    ZombieHiruko            "Zombie Hiruko"             0x145,
    HirukoII                "Hiruko II"                 0x146,
    AllFour                 "All Four"                  0x147,
    TakumiVI                "Takumi VI"                 0x148,
    HirukoVI                "Hiruko VI"                 0x149,
    Hirukos                 "Hirukos"                   0x14A,
    Shadow                  "Shadow"                    0x14C,
    GieQueen                "G'ie Queen"                0x14D,
    FB                      "FB"                        0x14E,
    All2                    "Everyone"                  0x14F, // All
    NigouQuestion           "Nigou?"                    0x150,
    Goldie                  "Goldie"                    0x151,
    NozomiII                "Nozomi II"                 0x152,
    TakumiG                 "Takumi-G"                  0x153,
    Gie                     "G'ie"                      0x154,
    TakumiVII               "Takumi VII"                0x155,
    HirukoVII               "Hiruko VII"                0x156,
    TheCurse                "The Curse"                 0x157,
    Boy                     "Boy"                       0x158,
    Girl                    "Girl"                      0x159,
    Kid                     "Kid"                       0x15A,
    FemaleStudent           "Female Student"            0x15B,
    YoungWoman              "Young Woman"               0x15C,
    MiddleAgedMan           "Middle-Aged Man"           0x15D,
    MiddleAgedWoman         "Middle-Aged Woman"         0x15E,
    OldMan                  "Old Man"                   0x15F,
    OldWoman                "Old Woman"                 0x160,
    EvaQuestion             "Eva?"                      0x161,
    MokoQuestion            "Moko?"                     0x162,
    VexhnessII              "V'ehxness II"              0x163,
    SponsorUnused           "Sponsor (Unused)"          0x164,
    EvasVoice               "Eva's Voice"               0x165,
    KakosVoice              "Kako's Voice"              0x166,
    Creature                "Creature"                  0x167,
    X                       "X"                         0x168,
    Retsnom                 "Retsnom"                   0x169,
    HolyJumonjiSword        "Holy Jumonji Sword"        0x16A,
    Darumarr                "Darumarr"                  0x16B,
    StrangeInvader          "Strange Invader"           0x16C,
    TakumiQuestionUnused    "Takumi? (Unused)"          0x16D,
    EitoAotsuki2            "Eito Aotsuki 2"            0x16E,
    EitoAotsuki3            "Eito Aotsuki 3"            0x16F,
    EitoAotsuki4            "Eito Aotsuki 4"            0x170,
    EitoAotsuki5            "Eito Aotsuki 5"            0x171,
    EitoAotsuki6            "Eito Aotsuki 6"            0x172,
    Interviewer             "Interviewer"               0x173,
    Announcement2           "Announcement"              0x174,
    TakumiQuestion          "Takumi?"                   0x175,
    HirukoQuestion          "Hiruko?"                   0x176,
    Sponsor2Unused          "Sponsor 2 (Unused)"        0x177,
    Sponsor3Unused          "Sponsor 3 (Unused)"        0x178,
    Sponsor4Unused          "Sponsor 4 (Unused)"        0x179,
    Sponsor5Unused          "Sponsor 5 (Unused)"        0x17A,
    Sponsor6Unused          "Sponsor 6 (Unused)"        0x17B,
    Gotoh                   "Gotoh"                     0x17D,
    GiesVoice               "G'ie's Voice"              0x17E,
    Scream                  "Scream"                    0x17F,
    StrangeVoice            "Strange Voice"             0x180,
    VexhnessAndVexhnessII   "V'ehxness & V'ehxness II"  0x181,
    SponsorKakoGUnused      "Sponsor - Kako-G (Unused)" 0x182,
    SponsorEitoUnused       "Sponsor - Eito (Unused)"   0x183,
    KakoAndIma              "Kako & Ima"                0x184,
    ImaAndKako              "Ima & Kako"                0x185,
    TakemaruAndShouma       "Takemaru & Shouma"         0x186,
    TsubasaKyoshikaYugamu   "Tsubasa/Kyoshika/Yugamu"   0x187,
    KuraraAndNozomi         "Kurara & Nozomi"           0x188,
    NigouAndEva             "Nigou & Eva"               0x189,
    Futuran1                "Futuran 1"                 0x18A,
    Futuran2                "Futuran 2"                 0x18B,
    Futuran3                "Futuran 3"                 0x18C,
    MokoAndKurara           "Moko & Kurara"             0x18D,
    TakumiAndHiruko         "Takumi & Hiruko"           0x18E,

/*
    BattleTakumiSumino                       "Takumi Sumino"                 0xF468D,
    BattleTakemaruYakushiji                  "Takemaru Yakushiji"            0xF4A75,
    BattleHirukoShizuhara                    "Hiruko Shizuhara"              0xF4E5D,
    BattleDarumiAmemiya                      "Darumi Amemiya"                0xF5245,
    BattleEitoAotsuki                        "Eito Aotsuki"                  0xF562D,
    BattleEitoAotsuki2                       "Eito Aotsuki"                  0xF562E,
    BattleTsubasaKawana                      "Tsubasa Kawana"                0xF5A15,
    BattleGakuMaruko                         "Gaku Maruko"                   0xF5DFD,
    BattleImaTsukumo                         "Ima Tsukumo"                   0xF61E5,
    BattleKakoTsukumo                        "Kako Tsukumo"                  0xF65CD,
    BattleShoumaGinzaki                      "Shouma Ginzaki"                0xF69B5,
    BattleNozomiKirifuji                     "Nozomi Kirifuji"               0xF6D9D,
    BattleNozomiKirifuji2                    "Nozomi Kirifuji"               0xF6D9E,
    BattleKuraraOosuzuki                     "Kurara Oosuzuki"               0xF7185,
    BattleKuraraOosuzuki2                    "Kurara Oosuzuki"               0xF7186,
    BattleKyoshikaMagadori                   "Kyoshika Magadori"             0xF756D,
    BattleKyoshikaMagadori2                  "Kyoshika Magadori"             0xF756E,
    BattleYugamuOmokage                      "Yugamu Omokage"                0xF7955,
    BattleYugamuOmokage2                     "Yugamu Omokage"                0xF7956,
    BattleMokoMojiro                         "Moko Mojiro"                   0xF7D3D,
    BattleEva                                "Eva"                           0xF8125,
    BattleGhostBoy                           "Ghost Boy"                     0xF850D,
    BattleGhostBoy2                          "Ghost Boy"                     0xF850E,
    BattleSirei                              "Sirei"                         0xF88F5,
    BattleNigou                              "Nigou"                         0xF8CDD,
    BattleTubrilla                           "Tubrilla"                      0x1EAFDD,
    BattleTubrilla2                          "Tubrilla"                      0x1EAFDE,
    BattleShadowTubrilla                     "Shadow Tubrilla"               0x1EB041,
    BattleFakeTubrilla                       "Fake Tubrilla"                 0x1EB0A5,
    BattleCrazedTubrilla                     "Crazed Tubrilla"               0x1EB3C5,
    BattleTubrillaQ                          "Tubrilla?"                     0x1ED23D,
    BattleGrizzlei                           "Grizzlei"                      0x1ED6ED,
    BattleShadowGrizzlei                     "Shadow Grizzlei"               0x1ED751,
    BattleFakeGrizzlei                       "Fake Grizzlei"                 0x1ED7B5,
    BattleCrazedGrizzlei                     "Crazed Grizzlei"               0x1EDAD5,
    BattleGrizzleiQ                          "Grizzlei?"                     0x1EF94D,
    BattleMoggimog                           "Moggimog"                      0x1EFDFD,
    BattleShadowMoggimog                     "Shadow Moggimog"               0x1EFE61,
    BattleFakeMoggimog                       "Fake Moggimog"                 0x1EFEC5,
    BattleCrazedMoggimog                     "Crazed Moggimog"               0x1F01E5,
    BattleMoggimogQ                          "Moggimog?"                     0x1F205D,
    BattleTelepax                            "Telepax"                       0x1F250D,
    BattleShadowTelepax                      "Shadow Telepax"                0x1F2571,
    BattleFakeTelepax                        "Fake Telepax"                  0x1F25D5,
    BattleCrazedTelepax                      "Crazed Telepax"                0x1F28F5,
    BattleTelepaxQ                           "Telepax?"                      0x1F476D,
    BattleLagomortar                         "Lagomortar"                    0x1F4C1D,
    BattleShadowLagomortar                   "Shadow Lagomortar"             0x1F4C81,
    BattleFakeLagomortar                     "Fake Lagomortar"               0x1F4CE5,
    BattleCrazedLagomortar                   "Crazed Lagomortar"             0x1F5005,
    BattleLagomortarQ                        "Lagomortar?"                   0x1F6E7D,
    BattleDarumarr                           "Darumarr"                      0x1F732D,
    BattleDarumarr2                          "Darumarr"                      0x1F732E,
    BattleDarumarr3                          "Darumarr"                      0x1F732F,
    BattleDarumarr4                          "Darumarr"                      0x1F7330,
    BattleDarumarr5                          "Darumarr"                      0x1F7331,
    BattleDarumarr6                          "Darumarr"                      0x1F7332,
    BattleDarumarr7                          "Darumarr"                      0x1F7333,
    BattleShadowDarumarr                     "Shadow Darumarr"               0x1F7334,
    BattleFakeDarumarr                       "Fake Darumarr"                 0x1F7335,
    BattleDarumarrQ                          "Darumarr?"                     0x1F958D,
    BattleDarumarrQ2                         "Darumarr?"                     0x1F958E,
    BattleDarumarrQ3                         "Darumarr?"                     0x1F958F,
    BattleDarumarrQ4                         "Darumarr?"                     0x1F9590,
    BattleDarumarrQ5                         "Darumarr?"                     0x1F9591,
    BattleDarumarrQ6                         "Darumarr?"                     0x1F9592,
    BattleYueffoh                            "Yueffoh"                       0x1F9A3D,
    BattleShadowYueffoh                      "Shadow Yueffoh"                0x1F9AA1,
    BattleFakeYueffoh                        "Fake Yueffoh"                  0x1F9B05,
    BattleCrazedYueffoh                      "Crazed Yueffoh"                0x1F9E25,
    BattleBuzztop                            "Buzztop"                       0x1FC14D,
    BattleShadowBuzztop                      "Shadow Buzztop"                0x1FC1B1,
    BattleFakeBuzztop                        "Fake Buzztop"                  0x1FC215,
    BattleCrazedBuzztop                      "Crazed Buzztop"                0x1FC535,
    BattleBuzztopQ                           "Buzztop?"                      0x1FE3AD,
    BattleBatrakkiken                        "Batrakkiken"                   0x1FE85D,
    BattleShadowBatrakkiken                  "Shadow Batrakkiken"            0x1FE8C1,
    BattleFakeBatrakkiken                    "Fake Batrakkiken"              0x1FE925,
    BattleCrazedBatrakkiken                  "Crazed Batrakkiken"            0x1FEC45,
    BattleBatrakkikenQ                       "Batrakkiken?"                  0x200ABD,
    BattleYurindah                           "Yurindah"                      0x200F6D,
    BattleShadowYurindah                     "Shadow Yurindah"               0x200FD1,
    BattleFakeYurindah                       "Fake Yurindah"                 0x201035,
    BattleCrazedYurindah                     "Crazed Yurindah"               0x201355,
    BattleYurindahQ                          "Yurindah?"                     0x2031CD,
    BattleSupremeCorpsSoldier                "Supreme Corps Soldier"         0x20367D,
    BattleVehxnessCorpsSoldier               "V'ehxness Corps Soldier"       0x203687,
    BattleMistifier                          "Mistifier"                     0x205D8D,
    BattleNoizmacher                         "Noizmacher"                    0x20849D,
    BattleEnemyCommander                     "Enemy Commander"               0x2650FD,
    BattleEnemyCommander2                    "Enemy Commander"               0x2650FE,
    BattleMurvrum                            "Murvrum"                       0x265107,
    BattleSquadTwoCommander                  "Squad Two Commander"           0x26780D,
    BattleSquadTwoCommanderQ                 "Squad Two Commander?"          0x26780E,
    BattleSquadTwoCommanderQ2                "Squad Two Commander?"          0x26780F,
    BattleSquadTwoCommanderQ3                "Squad Two Commander?"          0x267810,
    BattleSquadTwoCommanderQ4                "Squad Two Commander?"          0x267811,
    BattlePakron                             "Pakron"                        0x267817,
    BattleSquadTwoCommanderQ5                "Squad Two Commander?"          0x267818,
    BattleSquadTwoCommanderQ6                "Squad Two Commander?"          0x267819,
    BattleSquadTwoCommanderQ7                "Squad Two Commander?"          0x26781A,
    BattlePakronQ                            "Pakron?"                       0x269A77,
    BattleSquadThreeCommander                "Squad Three Commander"         0x269F1D,
    BattleAddamaque                          "Addamaque"                     0x269F27,
    BattleAddamaqueQ                         "Addamaque?"                    0x26C187,
    BattleSquadThreeCommanderQ               "Squad Three Commander?"        0x26C188,
*/
    BattleSquadFourCommander                 "Squad Four Commander"          0x26C62D, // Quenzelle
/*
BattleSquadFourCommanderMk2              "Squad Four Commander Mk.2"     0x26C62E,
    BattleQuenzelle                          "Quenzelle"                     0x26C638,
    BattleStrangeEgg                         "Strange Egg"                   0x26CDFD,
    BattleStrangeEgg2                        "Strange Egg"                   0x26CDFE,
    BattleStrangeEgg3                        "Strange Egg"                   0x26CDFF,
    BattleStrangeEgg4                        "Strange Egg"                   0x26CE00,
    BattleStrangeEgg5                        "Strange Egg"                   0x26CE01,
    BattleStrangeEgg6                        "Strange Egg"                   0x26CE02,
    BattleStrangeEgg7                        "Strange Egg"                   0x26CE03,
    BattleStrangeEgg8                        "Strange Egg"                   0x26CE07,
    BattleStrangeEgg9                        "Strange Egg"                   0x26CE08,
    BattleStrangeEgg10                       "Strange Egg"                   0x26CE09,
    BattleStrangeEgg11                       "Strange Egg"                   0x26CE0A,
    BattleStrangeEgg12                       "Strange Egg"                   0x26CE0B,
    BattleStrangeEgg13                       "Strange Egg"                   0x26CE0C,
    BattleStrangeEgg14                       "Strange Egg"                   0x26CE0D,
    BattleQuenzelleQ                         "Quenzelle?"                    0x26E898,
    BattleSquadFourCommanderQ                "Squad Four Commander?"         0x26E899,
    BattleSquadFiveCommander                 "Squad Five Commander"          0x26ED3D,
    BattleSquadFiveCommanderMk2              "Squad Five Commander Mk.2"     0x26ED3E,
    BattleParmith                            "Parmith"                       0x26ED47,
    BattleParmith2                           "Parmith"                       0x26ED48,
    BattleSquadFiveCommander2                "Squad Five Commander"          0x26ED49,
    BattleParmithQ                           "Parmith?"                      0x270FA7,
    BattleSquadSixCommander                  "Squad Six Commander"           0x27144D,
    BattleSquadSixCommander2                 "Squad Six Commander"           0x271457,
    BattleEva2                               "Eva"                           0x271458,
    BattleZenTa                              "Zen'ta"                        0x273B5D,
    BattleMokoQ                              "Moko?"                         0x273B5E,
    BattleEitoMonster                        "Eito Monster"                  0x273B5F,
    BattleMokoMonster                        "Moko Monster"                  0x273B60,
    BattleSquadEightCommander                "Squad Eight Commander"         0x27626D,
    BattleVallaGarzo                         "Valla-Garzo"                   0x276277,
    BattleSquadNineCommander                 "Squad Nine Commander"          0x27897D,
    BattleSquadNineCommander2                "Squad Nine Commander"          0x27897E,
    BattleSquadNineCommander3                "Squad Nine Commander"          0x27897F,
    BattleVallaGarshin                       "Valla-Garshin"                 0x278980,
    BattleSquadNineCommander4                "Squad Nine Commander"          0x278981,
    BattleSzanshin                           "Szanshin"                      0x278987,
    BattleSquadTenCommander                  "Squad Ten Commander"           0x27B08D,
    BattleNyewgank                           "Nyewgank"                      0x27B097,
    BattleSquadElevenCommander               "Squad Eleven Commander"        0x27D79D,
    BattleTuramtammi                         "Turamtammi"                    0x27D7A7,
    BattleTuramtammi2                        "Turamtammi"                    0x27D7A8,
    BattleDahlXia                            "Dahl'xia"                      0x27FEAD,
    BattleDahlXia2                           "Dahl'xia"                      0x27FEAE,
    BattleUnknown                            "???"                           0x280295,
    BattleStrangeEnemy                       "Strange Enemy"                 0x2825BD,
*/
    BattleSupremeCommander                   "Supreme Commander"             0x2825BE, // V'ehxness
/*
    BattleSupremeCommander2                  "Supreme Commander"             0x2825BF,
    BattleVehxness                           "V'ehxness"                     0x2825C0,
    BattleVehxness2                          "V'ehxness"                     0x2825C1,
    BattleVehxness3                          "V'ehxness"                     0x2825C2,
    BattleVehxness4                          "V'ehxness"                     0x2825C3,
    BattleVehxness5                          "V'ehxness"                     0x2825C4,
    BattleOtherVehxness                      "Other V'ehxness"               0x2825C5,
    BattleOtherVehxness2                     "Other V'ehxness"               0x2825C6,
    BattleVehxness6                          "V'ehxness"                     0x2825C7,
    BattleVehxness7                          "V'ehxness"                     0x2825C8,
    BattleVehxness8                          "V'ehxness"                     0x2825C9,
    BattleVehxness9                          "V'ehxness"                     0x2825CA,
    BattleEitoAotsuki3                       "Eito Aotsuki"                  0x284CCD,
    BattleEitoAotsuki4                       "Eito Aotsuki"                  0x284CCE,
    BattleEitoAotsuki5                       "Eito Aotsuki"                  0x284CCF,
    BattleNigou2                             "Nigou"                         0x2873E7,
    BattleShion                              "Shion"                         0x28C1FD,
    BattleShion2                             "Shion"                         0x28C1FE,
    BattleShion3                             "Shion"                         0x28C1FF,
    BattleBogusRocket                        "Bogus Rocket"                  0x2DBF55,
    BattleBarrierGenerator                   "Barrier Generator"             0x2DC33D,
    BattleTakumiSumino2                      "Takumi Sumino"                 0x2DCAA9,
    BattleTakumiCopy                         "Takumi Copy"                   0x2DCAB3,
    BattleTakumiCopy2                        "Takumi Copy"                   0x2DCAB4,
    BattleTakemaruYakushiji2                 "Takemaru Yakushiji"            0x2DCE91,
    BattleTakemaruCopy                       "Takemaru Copy"                 0x2DCE9B,
    BattleTakemaruCopy2                      "Takemaru Copy"                 0x2DCE9C,
    BattleHirukoShizuhara2                   "Hiruko Shizuhara"              0x2DD279,
    BattleHirukoCopy                         "Hiruko Copy"                   0x2DD283,
    BattleHirukoCopy2                        "Hiruko Copy"                   0x2DD284,
    BattleDarumiAmemiya2                     "Darumi Amemiya"                0x2DD661,
    BattleDarumiCopy                         "Darumi Copy"                   0x2DD66B,
    BattleDarumiCopy2                        "Darumi Copy"                   0x2DD66C,
    BattleEitoAotsuki6                       "Eito Aotsuki"                  0x2DDA49,
    BattleEitoCopy                           "Eito Copy"                     0x2DDA4A,
    BattleEitoAotsuki7                       "Eito Aotsuki"                  0x2DDA4B,
    BattleEitoQ                              "Eito?"                         0x2DDA4C,
    BattleEitoAotsuki8                       "Eito Aotsuki"                  0x2DDA4D,
    BattleEitoAotsuki9                       "Eito Aotsuki"                  0x2DDA4E,
    BattleEitoCopy2                          "Eito Copy"                     0x2DDA53,
    BattleEitoCopy3                          "Eito Copy"                     0x2DDA54,
    BattleTsubasaKawana2                     "Tsubasa Kawana"                0x2DDE31,
    BattleTsubasaCopy                        "Tsubasa Copy"                  0x2DDE3B,
    BattleTsubasaCopy2                       "Tsubasa Copy"                  0x2DDE3C,
    BattleGakuMaruko2                        "Gaku Maruko"                   0x2DE219,
    BattleGakuCopy                           "Gaku Copy"                     0x2DE223,
    BattleGakuCopy2                          "Gaku Copy"                     0x2DE224,
    BattleImaTsukumo2                        "Ima Tsukumo"                   0x2DE601,
    BattleImaCopy                            "Ima Copy"                      0x2DE60B,
    BattleImaCopy2                           "Ima Copy"                      0x2DE60C,
    BattleKakoTsukumo2                       "Kako Tsukumo"                  0x2DE9E9,
    BattleKakoCopy                           "Kako Copy"                     0x2DE9F3,
    BattleKakoCopy2                          "Kako Copy"                     0x2DE9F4,
    BattleShoumaGinzaki2                     "Shouma Ginzaki"                0x2DEDD1,
    BattleShoumaCopy                         "Shouma Copy"                   0x2DEDDB,
    BattleShoumaCopy2                        "Shouma Copy"                   0x2DEDDC,
    BattleNozomiKirifuji3                    "Nozomi Kirifuji"               0x2DF1B9,
    BattleNozomiKirifuji4                    "Nozomi Kirifuji"               0x2DF1BA,
    BattleNozomiCopy                         "Nozomi Copy"                   0x2DF1C3,
    BattleNozomiCopy2                        "Nozomi Copy"                   0x2DF1C4,
    BattleKuraraOosuzuki3                    "Kurara Oosuzuki"               0x2DF5A1,
    BattleKuraraOosuzuki4                    "Kurara Oosuzuki"               0x2DF5A2,
    BattleKuraraCopy                         "Kurara Copy"                   0x2DF5AB,
    BattleKuraraCopy2                        "Kurara Copy"                   0x2DF5AC,
    BattleKyoshikaMagadori3                  "Kyoshika Magadori"             0x2DF989,
    BattleKyoshikaMagadori4                  "Kyoshika Magadori"             0x2DF98A,
    BattleKyoshikaCopy                       "Kyoshika Copy"                 0x2DF993,
    BattleKyoshikaCopy2                      "Kyoshika Copy"                 0x2DF994,
    BattleYugamuOmokage3                     "Yugamu Omokage"                0x2DFD71,
    BattleYugamuOmokage4                     "Yugamu Omokage"                0x2DFD72,
    BattleYugamuCopy                         "Yugamu Copy"                   0x2DFD7B,
    BattleYugamuCopy2                        "Yugamu Copy"                   0x2DFD7C,
    BattleMokoMojiro2                        "Moko Mojiro"                   0x2E0159,
    BattleMokoMojiro3                        "Moko Mojiro"                   0x2E015A,
    BattleMokoCopy                           "Moko Copy"                     0x2E0163,
    BattleMokoCopy2                          "Moko Copy"                     0x2E0164,
    BattleEva3                               "Eva"                           0x2E0541,
    BattleEvaCopy                            "Eva Copy"                      0x2E054B,
    BattleEvaCopy2                           "Eva Copy"                      0x2E054C,
    BattleMetalFence                         "Metal Fence"                   0x3D0965,
    BattleMetalFenceLv2                      "Metal Fence Lv.2"              0x3D0966,
    BattleMetalFenceLv3                      "Metal Fence Lv.3"              0x3D0967,
    BattleMetalFenceLv4                      "Metal Fence Lv.4"              0x3D0968,
    BattleMetalFenceLv5                      "Metal Fence Lv.5"              0x3D0969,
    BattleMetalFenceLv6                      "Metal Fence Lv.6"              0x3D096A,
    BattleMetalFenceLv7                      "Metal Fence Lv.7"              0x3D096B,
    BattleMetalFenceLv8                      "Metal Fence Lv.8"              0x3D096C,
    BattleMetalFenceLv9                      "Metal Fence Lv.9"              0x3D096D,
    BattleMetalFenceMax                      "Metal Fence MAX"               0x3D096E,
    BattleElectrifiedFence                   "Electrified Fence"             0x3D09C9,
    BattleElectrifiedFenceLv2                "Electrified Fence Lv.2"        0x3D09CA,
    BattleElectrifiedFenceLv3                "Electrified Fence Lv.3"        0x3D09CB,
    BattleElectrifiedFenceLv4                "Electrified Fence Lv.4"        0x3D09CC,
    BattleElectrifiedFenceLv5                "Electrified Fence Lv.5"        0x3D09CD,
    BattleElectrifiedFenceLv6                "Electrified Fence Lv.6"        0x3D09CE,
    BattleElectrifiedFenceLv7                "Electrified Fence Lv.7"        0x3D09CF,
    BattleElectrifiedFenceLv8                "Electrified Fence Lv.8"        0x3D09D0,
    BattleElectrifiedFenceLv9                "Electrified Fence Lv.9"        0x3D09D1,
    BattleElectrifiedFenceMax                "Electrified Fence MAX"         0x3D09D2,
    BattleExplosiveMine                      "Explosive Mine"                0x3D0A2D,
    BattleExplosiveMineLv2                   "Explosive Mine Lv.2"           0x3D0A2E,
    BattleExplosiveMineLv3                   "Explosive Mine Lv.3"           0x3D0A2F,
    BattleExplosiveMineLv4                   "Explosive Mine Lv.4"           0x3D0A30,
    BattleExplosiveMineLv5                   "Explosive Mine Lv.5"           0x3D0A31,
    BattleExplosiveMineLv6                   "Explosive Mine Lv.6"           0x3D0A32,
    BattleExplosiveMineLv7                   "Explosive Mine Lv.7"           0x3D0A33,
    BattleExplosiveMineLv8                   "Explosive Mine Lv.8"           0x3D0A34,
    BattleExplosiveMineLv9                   "Explosive Mine Lv.9"           0x3D0A35,
    BattleExplosiveMineMax                   "Explosive Mine MAX"            0x3D0A36,
    BattleMountedTurret                      "Mounted Turret"                0x3D0A91,
    BattleMountedTurretLv2                   "Mounted Turret Lv.2"           0x3D0A92,
    BattleMountedTurretLv3                   "Mounted Turret Lv.3"           0x3D0A93,
    BattleMountedTurretLv4                   "Mounted Turret Lv.4"           0x3D0A94,
    BattleMountedTurretMax                   "Mounted Turret MAX"            0x3D0A95,
    BattleKuraraBomb                         "Kurara Bomb"                   0x3D0AF5,
    BattleKuraraBombLv2                      "Kurara Bomb Lv.2"              0x3D0AF6,
    BattleKuraraBombLv3                      "Kurara Bomb Lv.3"              0x3D0AF7,
    BattleKuraraBombLv4                      "Kurara Bomb Lv.4"              0x3D0AF8,
    BattleKuraraBombLv5                      "Kurara Bomb Lv.5"              0x3D0AF9,
    BattleKuraraBombLv6                      "Kurara Bomb Lv.6"              0x3D0AFA,
    BattleKuraraBombLv7                      "Kurara Bomb Lv.7"              0x3D0AFB,
    BattleKuraraBombLv8                      "Kurara Bomb Lv.8"              0x3D0AFC,
    BattleKuraraBombLv9                      "Kurara Bomb Lv.9"              0x3D0AFD,
    BattleKuraraBombLv10                     "Kurara Bomb Lv.10"             0x3D0AFE,
    BattleKuraraBombMax                      "Kurara Bomb MAX"               0x3D0AFF,
    BattleSupportTower                       "Support Tower"                 0x3D0B59,
    BattleSupportTowerLv2                    "Support Tower Lv.2"            0x3D0B5A,
    BattleSupportTowerLv3                    "Support Tower Lv.3"            0x3D0B5B,
    BattleSupportTowerLv4                    "Support Tower Lv.4"            0x3D0B5C,
    BattleSupportTowerMax                    "Support Tower MAX"             0x3D0B5D,
    BattleBarrierGenerator2                  "Barrier Generator"             0x3D0D4D,
    BattleSchoolBus                          "School Bus"                    0x3D0D4E,
    BattleKaruaKashimiya                     "Karua Kashimiya"               0x3D0D52,
    BattleArtilleryInProgress                "Artillery (In Progress)"       0x3D0D53,
    BattleArtilleryComplete                  "Artillery (Complete)"          0x3D0D54,
    BattleBrokenMissile                      "Broken Missile"                0x3D0D56,
    BattlePoisonTrap                         "Poison Trap"                   0x3D0D57,
    BattleTrapBarrier                        "Trap Barrier"                  0x3D0D58,
    BattleRocket                             "Rocket"                        0x3D0D59,
    BattleEnemyBaseExplosive                 "Enemy Base Explosive"          0x3D0D5A,
    BattleVehxnessCorpsSoldier2              "V'ehxness Corps Soldier"       0x3D0D5B,
    BattleVehxnessCorpsSoldier3              "V'ehxness Corps Soldier"       0x3D0D5C,
    BattleEitoAotsuki10                      "Eito Aotsuki"                  0x3D0D5D,
    BattleMokoMojiro4                        "Moko Mojiro"                   0x3D0D5E,
    BattleBarrierGenerator3                  "Barrier Generator"             0x3D0D5F,
    BattleBarrierGenerator4                  "Barrier Generator"             0x3D0D60,
    BattleRocket2                            "Rocket"                        0x3D0D61,
    BattleMissileI                           "Missile I"                     0x3D0DB1,
    BattleMissileII                          "Missile II"                    0x3D0DB2,
    BattleMissileIII                         "Missile III"                   0x3D0DB3,
    BattleMissileIV                          "Missile IV"                    0x3D0DB4,
    BattleMissileV                           "Missile V"                     0x3D0DB5,
    BattleMissileVI                          "Missile VI"                    0x3D0DB6,
    BattleMissileVII                         "Missile VII"                   0x3D0DB7,
    BattleMissileVIII                        "Missile VIII"                  0x3D0DB8,
    BattleMissileIX                          "Missile IX"                    0x3D0DB9,
    BattleMissileX                           "Missile X"                     0x3D0DBA,
    BattleN3DModel                           "3D Model"                      0x895829,
    BattleParallaxOcclusion                  "Parallax Occlusion"            0x89582A,
*/
    Text                    "Text"                      0xCCCCCCCC
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum PlaceholderOrCharacter {
    Character(Character),
    Placeholder(u32),
}

impl PlaceholderOrCharacter {
    pub fn name(self) -> Cow<'static, str> {
        match self {
            Self::Character(c) => Cow::Borrowed(c.name()),
            Self::Placeholder(p) => Cow::Owned(format!("Unknown character {p:#x}")),
        }
    }
}

impl From<u32> for PlaceholderOrCharacter {
    fn from(value: u32) -> Self {
        match Character::from_u32(value) {
            Some(x) => Self::Character(x),
            None => Self::Placeholder(value),
        }
    }
}
impl From<PlaceholderOrCharacter> for u32 {
    fn from(value: PlaceholderOrCharacter) -> Self {
        match value {
            PlaceholderOrCharacter::Character(x) => x as u32,
            PlaceholderOrCharacter::Placeholder(x) => x,
        }
    }
}
